version: "3.7"
services:
  db:
    image: postgres:12.2
    restart: on-failure
    ports:
      - 7120:5432
    volumes:
      - db-fullprojekt-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime
    environment:
      POSTGRES_USER: hozdemir
      POSTGRES_PASSWORD: sql000
      POSTGRES_DB: fullprojekt

  db-test:
    image: postgres:12.2
    restart: on-failure
    ports:
      - 7121:5432
    volumes:
      - db-fullprojekt-data-test:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime
    environment:
      POSTGRES_USER: hozdemir
      POSTGRES_PASSWORD: sql000
      POSTGRES_DB: fullprojekt

volumes:
  db-fullprojekt-data:
    driver: local

  db-fullprojekt-data-test:
    driver: local

